# Output
output_folder: bumonkey_hashenc
experiment_name: hashenc
# Model options
r: 192
depth: 2
n_levels: 11
n_features_per_level: 2
log2_hashmap_size: 25
base_resolution: 18
lambda_c: 0.0
#test
iter: 5000

